//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATA_TRANSFERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DATA_TRANSFERS()
        {
            this.DATA_STAT_HOSPITALIZATION = new HashSet<DATA_STAT_HOSPITALIZATION>();
        }
    
        public int DATA_TRANSFERS_ID { get; set; }
        public Nullable<System.DateTime> ARRIVE_DATE { get; set; }
        public Nullable<System.DateTime> DEPART_DATE { get; set; }
        public Nullable<int> FK_HO_BED_ID { get; set; }
        public Nullable<int> FK_HO_RESERV_ID { get; set; }
        public Nullable<int> FK_PATIENTS_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATA_STAT_HOSPITALIZATION> DATA_STAT_HOSPITALIZATION { get; set; }
        public virtual HO_BED HO_BED { get; set; }
        public virtual HO_RESERV HO_RESERV { get; set; }
        public virtual PATIENTS PATIENTS { get; set; }
    }
}
