//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATA_DIAGNOSIS
    {
        public int DATA_DIAGNOSIS_ID { get; set; }
        public Nullable<System.DateTime> DATE_CONSULTATION { get; set; }
        public Nullable<int> FK_DIAGNOZ_ID { get; set; }
        public Nullable<int> FK_MOTCONSUU_ID { get; set; }
    
        public virtual DIAGNOZ DIAGNOZ { get; set; }
        public virtual MOTCONSU MOTCONSU { get; set; }
    }
}
