//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATA_STAT_HOSPITALIZATION
    {
        public int DATA_STAT_HOSPITALIZATION_ID { get; set; }
        public Nullable<int> PROVEDENO_KOJKO_DNEJ { get; set; }
        public string KEM_DOSTAVLEN { get; set; }
        public Nullable<int> FK_ED_TREATMENT_RESULTS_ID { get; set; }
        public Nullable<int> FK_ED_PATIENTS_STATUS_ID { get; set; }
        public Nullable<int> FK_DATA_TRANSFERS_ID { get; set; }
        public Nullable<int> FK_MEDECINS_ID { get; set; }
    
        public virtual DATA_TRANSFERS DATA_TRANSFERS { get; set; }
        public virtual ED_TREATMENT_RESULTS ED_TREATMENT_RESULTS { get; set; }
        public virtual ED_PATIENTS_STATUS ED_PATIENTS_STATUS { get; set; }
        public virtual MEDECINS MEDECINS { get; set; }
    }
}
