//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HO_BED
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HO_BED()
        {
            this.DATA_TRANSFERS = new HashSet<DATA_TRANSFERS>();
        }
    
        public int HO_BED_ID { get; set; }
        public string LABEL { get; set; }
        public string READY { get; set; }
        public Nullable<int> FK_HO_ROOM_ID { get; set; }
        public Nullable<int> FK_HO_BED_TYPE_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATA_TRANSFERS> DATA_TRANSFERS { get; set; }
        public virtual HO_BED_TYPE HO_BED_TYPE { get; set; }
        public virtual HO_ROOM HO_ROOM { get; set; }
    }
}
