//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HO_ROOM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HO_ROOM()
        {
            this.HO_BED = new HashSet<HO_BED>();
        }
    
        public int HO_ROOM_ID { get; set; }
        public string LABEL { get; set; }
        public Nullable<int> FLOOR { get; set; }
        public Nullable<int> FK_MEDDEP_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HO_BED> HO_BED { get; set; }
        public virtual MEDDEP MEDDEP { get; set; }
    }
}
