//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDDEP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEDDEP()
        {
            this.HO_RESERV = new HashSet<HO_RESERV>();
            this.HO_ROOM = new HashSet<HO_ROOM>();
        }
    
        public int MEDDEP_ID { get; set; }
        public Nullable<int> FK_MEDECINS_ID { get; set; }
        public Nullable<int> FK_FM_DEP_ID { get; set; }
        public Nullable<int> FK_VID_STACIONARA_ID { get; set; }
    
        public virtual FM_DEP FM_DEP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HO_RESERV> HO_RESERV { get; set; }
        public virtual MEDECINS MEDECINS { get; set; }
        public virtual VID_STACIONARA VID_STACIONARA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HO_ROOM> HO_ROOM { get; set; }
    }
}
