//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOTCONSU_EVENT_TYPES
    {
        public int MOTCONSU_EVENT_TYPES_ID { get; set; }
        public string LABEL { get; set; }
    }
}
