//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PATIENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PATIENTS()
        {
            this.DATA_TRANSFERS = new HashSet<DATA_TRANSFERS>();
            this.MOTCONSU = new HashSet<MOTCONSU>();
        }
    
        public int PATIENTS_ID { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
        public string PATROMYME { get; set; }
        public Nullable<System.DateTime> DATA_SMERTI { get; set; }
        public Nullable<int> POL { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> NONRESIDENT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATA_TRANSFERS> DATA_TRANSFERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOTCONSU> MOTCONSU { get; set; }
    }
}
