//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PL_EXAM
    {
        public int PL_EXAM_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> DUREE { get; set; }
        public string PRINT_LABLE { get; set; }
    }
}
