//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANNING
    {
        public int PLANNING_ID { get; set; }
        public Nullable<System.DateTime> DATE_CONS { get; set; }
        public string COMMENTARIE { get; set; }
    }
}
