//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int Users_ID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Login { get; set; }
        public Nullable<int> FKRoleID { get; set; }
        public Nullable<bool> isBlocked { get; set; }
        public Nullable<System.DateTime> dateCreatedPass { get; set; }
        public Nullable<bool> isDropped { get; set; }
        public Nullable<int> PasswordCountAttempt { get; set; }
        public string Email { get; set; }
        public string HashPass { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
